### ISSUE TITLE
Not working! Android Nougat + VLC

### ISSUE THREAD

**Issue by harounhajem** [thiolliere/YouTubeStream#2]
Hi! 

It's not working, when i switch off the screen the stream is paused. 
I copy the video link from Youtube to your app, then it opens VLC with that stream. 
Then i close the screen and the stream is paused.

**Comment by thiolliere** [comment]
To put a video in background on VLC you have to touch the 3 dots to open menu and then the rectangle with a line in diagonal indicating no screen.

Maybe I should indicate it in the description, I don't know.

**Comment by harounhajem** [comment]
You are right, found it under the three dots menu.

**Comment by thiolliere** [comment]
by the way I think you can set default behavior to the behavior you want in the setting
